spring:
  datasource:
    #连接MySQL useSSL=false& 搞懂每个参数意义
    url: jdbc:mysql://localhost:3306/website?allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: admin
    password: eternal2002@
    driver-class-name: com.mysql.cj.jdbc.Driver

#  # 这是ehcache 2的配置方式：https://memorynotfound.com/spring-boot-ehcache-2-caching-example-configuration/
#  cache:
#    ehcache:
#      config: ehcache2.xml

  # ehcache 3的配置方式
  cache:
    jcache:
      config: classpath:ehcache.xml

  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/


#mybatis:
#  config-location: mybatis-config.xml
##  mapper-locations: mapper/*.xml
##  config-location: classpath:mybatis-config.xml
##  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
#    map-underscore-to-camel-case: true
#    # logging.level.TAlarmInformationMapper=debug

#mybatis:
#  config-location: mybatis-config.xml
#
#mybatis-plus:
#  config-location: mybatis-config.xml

#mybatis-plus:
#  mapper-location: classpath*:/mapper/*Mapper.xml
#  type-aliases-package: com.greengiant.website.dao
#  global-config:
#    db-config:
#      id-type: AUTO
#      field-strategy: NOT_NULL
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#    #refresh: true
#  configuration:
#    ccahe-enabled: true
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# todo 配置druid，和mybatis-config.xml的配置有什么关联？

#logging:
#  level:
#    #打印SQL信息
#    com.hehe.mapper: debug

file:
  upload-path: d:/website-file/

# ------------------------------------------------------------------------------------

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"