spring:
  datasource:
    #连接MySQL useSSL=false& 搞懂每个参数意义
    url: jdbc:mysql://localhost:3306/website?allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: admin
    password: eternal2002@
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 要能够测出来有没有的区别
    cache:
      ehcache:
        config: ehcache.xml

#mybatis-plus:
#  mapper-location: classpath*:/mapper/*Mapper.xml
#  type-aliases-package: com.greengiant.*.pojo.model
#  global-config:
#    db-config:
#      id-type: AUTO
#      field-strategy: NOT_NULL
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#    #refresh: true
#  configuration:
#    cahe-enabled: true
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/,classpath:/static/, classpath:/public/,classpath:/templates/

mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true

# todo 配置druid

#logging:
#  level:
#    #打印SQL信息
#    com.hehe.mapper: debug

# ------------------------------------------------------------------------------------

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"