spring:
  datasource:
    #连接MySQL
    url: jdbc:mysql://localhost:3306/website?useSSL=false
    username: admin
    password: eternal2002@
    driver-class-name: com.mysql.cj.jdbc.Driver

#  # frontend
#  mvc:
#    view:
#      prefix: /views/
#      suffix: .html

mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true

# todo 配置druid
#logging:
#  level:
#    #打印SQL信息
#    com.hehe.mapper: debug

# ------------------------------------------------------------------------------------

# todo active profile



# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"